---
# install.yml
- name: Install required modules
  hosts: all
  become: true
  tasks:
    - name: Update cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install aptitude
      ansible.builtin.apt:
        name: aptitude
        state: present

    - name: Install required system packages
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
          - zip
        state: present

    - name: Add Docker GPG apt Key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
        state: present

    - name: Install docker
      ansible.builtin.apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present

    - name: Install Docker Module for Python
      ansible.builtin.pip:
        name: docker

    - name: Upgrade packages
      ansible.builtin.apt:
        upgrade: full

    - name: Start docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Enable ubuntu user to use docker
      ansible.builtin.user:
        name: ubuntu
        group: docker
